name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund

      - name: Build Project
        run: npm run build

      - name: Check dist
        run: |
          if [ ! -d "./dist" ]; then
            echo "Error: ./dist directory does not exist!"
            exit 1
          fi
          ls -la ./dist
          du -sh ./dist

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4      
